language: java

sudo: false

jdk:
    - oraclejdk8

env:
    - TERM=dumb

install:
  - pip install -r requirements.txt

script:
    - "./gradlew clean check -i --continue"

branches:
  only:
    - master

before_script:
    - "export PATH=$HOME/.local/bin:$PATH"

after_failure:
    - "python bugcomment.py"
