language: java

sudo: false

jdk:
    - oraclejdk8

env:
    - TERM=dumb

script:
    - "./gradlew clean check -i --continue"

branches:
  only:
    - master

before_script:
    - "export PATH=$HOME/.local/bin:$PATH"
    - "pip install -r requirements.txt --user `whoami`"

after_failure:
    - "python bugcomment.py"

addons:
  apt:
    packages:
      - python-pip
